import { BusinessOrigin, ProjectData, Period } from './types/projectTypes';

const defaultDaySchedule = {
  open: true,
  breakfast: { start: '07:00', end: '11:00' },
  lunch: { start: '11:00', end: '15:00' },
  dinner: { start: '17:00', end: '21:00' },
  prep: { start: '06:00', end: '07:00' },
  shutdown: { start: '21:00', end: '22:00' },
};

export function createEmptyProject(initialOrigin: BusinessOrigin = 'new'): ProjectData {
  return {
    period: 'Monthly' as Period,
    venueType: null,
    storeTown: null,
    expectedOpeningDate: null,
    seasonalityProfile: 'Flat',
    holidayBumpProfile: 'None',
    businessOrigin: initialOrigin,
    scenarioMode: 'single',
    fitoutMode: initialOrigin === 'existing' ? 'existingBusiness' : 'newFitout',
    timeFormatPreference: '12h',
    walkthroughStep: 1,
    stepStatus: {},
    referralFlags: {},
    siteName: null,
    siteAddress: null,
    siteListingUrl: null,
    operatingBreakEvenDate: null,
    ownersReturnBreakEvenDate: null,
    simpleBreakEven: {
      enteredSales: 0,
      ownersReturn: 0,
      rent: 0,
      variableCogs: 0,
      variableLabour: 0,
      variableOther: 0,
    },
    detailedBreakEven: {
      scenario1: {
        enteredSales: 0,
        ownersReturn: 0,
        rent: 0,
        labourMinimumCost: 0,
        variableCogs: 0,
        variableLabour: 0,
        variableOther: 0,
        insurance: 0,
        accounting: 0,
        marketing: 0,
        utilities: 0,
        otherFixed: 0,
        customFixedCosts: [],
        occupancyType: 'renting',
        loanType: 'principalAndInterest',
        propertyPurchasePrice: 0,
        propertyDeposit: 0,
        propertyClosingCosts: 0,
        propertyStampDuty: 0,
        propertyGstPayable: false,
        propertyInterestRate: 6.5,
        propertyLoanTerm: 25,
      },
      scenario2: {
        enteredSales: 0,
        ownersReturn: 0,
        rent: 0,
        labourMinimumCost: 0,
        variableCogs: 0,
        variableLabour: 0,
        variableOther: 0,
        insurance: 0,
        accounting: 0,
        marketing: 0,
        utilities: 0,
        otherFixed: 0,
        customFixedCosts: [],
        occupancyType: 'renting',
        loanType: 'principalAndInterest',
        propertyPurchasePrice: 0,
        propertyDeposit: 0,
        propertyClosingCosts: 0,
        propertyStampDuty: 0,
        propertyGstPayable: false,
        propertyInterestRate: 6.5,
        propertyLoanTerm: 25,
      },
      scenario3: {
        enteredSales: 0,
        ownersReturn: 0,
        rent: 0,
        labourMinimumCost: 0,
        variableCogs: 0,
        variableLabour: 0,
        variableOther: 0,
        insurance: 0,
        accounting: 0,
        marketing: 0,
        utilities: 0,
        otherFixed: 0,
        customFixedCosts: [],
        occupancyType: 'renting',
        loanType: 'principalAndInterest',
        propertyPurchasePrice: 0,
        propertyDeposit: 0,
        propertyClosingCosts: 0,
        propertyStampDuty: 0,
        propertyGstPayable: false,
        propertyInterestRate: 6.5,
        propertyLoanTerm: 25,
      },
    },
    fitoutFinancing: {
      scenario1: {
        name: 'Base Case',
        siteType: initialOrigin === 'existing' ? 'existing' : 'new',
        purchasePrice: initialOrigin === 'existing' ? 0 : undefined,
        equipment: 0,
        furniture: 0,
        tech: 0,
        stock: 0,
        fitout: 0,
        signage: 0,
        designFees: 0,
        legal: 0,
        operatingCapital: 0,
        customSetupCosts: [],
        startupCapital: 0,
        loanAmount: 0,
        loanInterest: 0,
        loanTerm: 0,
        balloonPercent: 0,
        repaymentFrequency: 'Monthly',
        equipmentRentalAmount: 0,
        occupancyType: 'renting',
        propertyPurchasePrice: 0,
        propertyDeposit: 0,
        propertyClosingCosts: 0,
        propertyStampDuty: 0,
        propertyGstPayable: false,
        propertyInterestRate: 6.5,
        propertyLoanTerm: 25,
      },
      scenario2: {
        name: 'Optimistic',
        siteType: initialOrigin === 'existing' ? 'existing' : 'new',
        purchasePrice: initialOrigin === 'existing' ? 0 : undefined,
        equipment: 0,
        furniture: 0,
        tech: 0,
        stock: 0,
        fitout: 0,
        signage: 0,
        designFees: 0,
        legal: 0,
        operatingCapital: 0,
        customSetupCosts: [],
        startupCapital: 0,
        loanAmount: 0,
        loanInterest: 0,
        loanTerm: 0,
        balloonPercent: 0,
        repaymentFrequency: 'Monthly',
        equipmentRentalAmount: 0,
        occupancyType: 'renting',
        propertyPurchasePrice: 0,
        propertyDeposit: 0,
        propertyClosingCosts: 0,
        propertyStampDuty: 0,
        propertyGstPayable: false,
        propertyInterestRate: 6.5,
        propertyLoanTerm: 25,
      },
      scenario3: {
        name: 'Conservative',
        siteType: initialOrigin === 'existing' ? 'existing' : 'new',
        purchasePrice: initialOrigin === 'existing' ? 0 : undefined,
        equipment: 0,
        furniture: 0,
        tech: 0,
        stock: 0,
        fitout: 0,
        signage: 0,
        designFees: 0,
        legal: 0,
        operatingCapital: 0,
        customSetupCosts: [],
        startupCapital: 0,
        loanAmount: 0,
        loanInterest: 0,
        loanTerm: 0,
        balloonPercent: 0,
        repaymentFrequency: 'Monthly',
        equipmentRentalAmount: 0,
        occupancyType: 'renting',
        propertyPurchasePrice: 0,
        propertyDeposit: 0,
        propertyClosingCosts: 0,
        propertyStampDuty: 0,
        propertyGstPayable: false,
        propertyInterestRate: 6.5,
        propertyLoanTerm: 25,
      },
    },
    hoursOfOperation: {
      monday: { ...defaultDaySchedule },
      tuesday: { ...defaultDaySchedule },
      wednesday: { ...defaultDaySchedule },
      thursday: { ...defaultDaySchedule },
      friday: { ...defaultDaySchedule },
      saturday: { ...defaultDaySchedule },
      sunday: { ...defaultDaySchedule },
    },
    salesBreakup: {
      weeklySales: 0,
      dayPercentages: {
        monday: 14.3,
        tuesday: 14.3,
        wednesday: 14.3,
        thursday: 14.3,
        friday: 14.3,
        saturday: 14.3,
        sunday: 14.3,
      },
      servicePercentages: {
        breakfast: 20,
        lunch: 40,
        dinner: 40,
      },
    },
    location: {
      address: null,
      propertySize: null,
      annualRent: null,
      frontageType: null,
      parkingQuality: null,
      visibility: null,
      nearbyActivity: null,
      catchmentStrength: null,
    },
    locationSuitabilityScore: null,
    orderSources: [
      { key: "orderInVenue" as const, label: "Order in Venue", percent: 100 }
    ],
  };
}
